#pragma once

unordered_map<ModuleID, pair<string, string>> module_descriptions
{
	{ AntiCapture, {"Excludes this client window from capture. (Require >= Win10)", "从截屏或录屏中排除此客户端的窗口（至少需要 Win10）"}},
	{ AntiClose, {"If enabled, close messages are invalid for this client window.", "屏蔽所有对本客户端窗口的关闭消息。"}},
	{ AntiDebug, {"Prevent this client from being debugged.", "防止客户端被调试。"}},
	{ AntiInject, {"Prevents from any module injection of this client.", "防止客户端进程被注入。"}},
	{ AntiIntercept, {"Prevents from any interception of antivirus softwares.", "自动对一些杀软的拦截窗口按允许。"}},
	{ AntiTaskkill, {"Prevents from any taskkill command to this client.", "阻止所有对客户端有威胁的taskkill命令。"}},
	{ AntiMouseHook, {"Prevents from any normal mouse hooking.", "阻止普通的鼠标钩子。"}},
    { AntiKeyHook, {"Prevents from any normal keyboard hooking.", "阻止普通的键盘钩子。"}},
	{ AutoUAC, {"Automatically press the yes button of the UAC prompt. ", "在UAC界面自动按“是”。"}},
	{ AutoLogin, {"Automatically input user's password in the login UI.", "在登录界面自动输入用户密码。"}},
	{ Admin, {"Granted with Admin privileges.", "重启客户端获得管理员权限。"}},
	{ System, {"Granted with System privileges.", "重启客户端窃取系统权限。"}},
	{ UIAccess, {"Granted with UIAccess token privilege. (System Required)", "重启客户端窃取UIAccess特权。（需要系统权限）"}},
	{ UACBypass, {"Bypasses the UAC prompt to obtain Admin privileges.", "绕过UAC弹窗获得管理员权限。"}},
	{ Taskmgr, {"Start the Task Manager.", "打开任务管理器。"}},
	{ Cmd, {"Start the Command Prompt.", "打开命令提示符。"}},
	{ PowerShell, {"Start the PowerShell.", "打开 PowerShell。"}},
	{ Gpedit, {"Start the Group Policy Editor.", "打开组策略编辑器。"}},
	{ Perfmon, {"Start the Performance Monitor.", "打开资源监视器。"}},
    { Regedit, {"Start the Registry Editor.", "打开注册表编辑器。"}},
	{ Osk, {"Start the On-Screen Keyboard.", "打开屏幕键盘。"}},
	{ Mrt, {"Start the Malicious Software Removal Tool.", "打开恶意程序删除工具。"}},
	{ CrackPassword, {"Brute Force the computer password of current user with a dictionary.", "凭借字典，暴力破解计算机当前用户的密码。"}},
	{ SetPassword, {"Clear or Set the login password of the user. (Admin Required)", "清除或设置计算机密码。（需要管理员）"}},
	{ ClearPin, {"Clear Windows PIN. (Reboot to Apply)", "清除 Windows PIN，重启生效。"}},
	{ Uninstaller, {"Automatically help you uninstall some softwares.", "自动帮你卸载一些软件。"}},
	{ Interceptor, {"Globally intercept some important functions in the system. (WIP)", "全局拦截系统的某些重要函数。 (维护中)"}},
	{ Gatekeeper, {"Intercept Winlogon Events by injecting a special DLL. (Admin + Privileges Required)", "通过注入动态链接库，拦截 Winlogon 事件（需要管理员和特权）"}},
	{ NoFirewall, {"Disable the Windows Firewall (No Admin Required).", "禁用系统防火墙（不需要管理员）"}},
	{ FreezeWinlogon, {"Suspend the winlogon.exe. Only works in lower versions of Windows.", "挂起 Winlogon。 只在低版本系统有效。"}},
	{ MagnifyReplace, {"Substitude the system Magnifier with the client. Press Win + = to start. (Admin Required)", "用本客户端的启动器替换系统放大镜。按下 Win + = 快捷启动。（需要管理员）"}},
	{ SethcBackdoor, {"Set the client as the Sethc Backdoor. Press Shift five times to start. (Admin Required)", "用本客户端的启动器替换系统粘滞键。按下五下 LShift 快捷启动。（需要管理员）"}},
	{ Privileges, {"Obtain all available privileges.", "获得各项可用的特权。"}},
	{ Protection, {"Prevent the client from being terminated by User functions. (RTCore64 Driver Needed)", "为客户端启用进程保护，可以阻止一切用户层的终止进程函数。（需要 RTCore64 驱动）"}},
	{ LockUser, {"Lock current user immediately.", "立即锁定当前用户。"}},
	{ Logoff, {"Logoff the current user immediately.", "立即注销。"}},
	{ Shutdown, {"Shutdown the system immediately.", "立即关机。"}},
	{ Reboot, {"Reboot the system immediately.", "立即重启。"}},
	{ MythwareKiller, {"Destroy all the restrictions of Mythware and Uninstall it." , "摧毁一切极域的限制然后卸载它。"}},
	{ Crash, {"Trigger BSOD to crash Windows (No Admin Required)." , "触发蓝屏使系统崩溃。（不需要管理员）"}},

	{ ListTrays, {"List all the info of trays inside the taskbar.", "枚举任务栏中的托盘信息。" }},
	{ WindowTags, {"Show window info tags in the left-top corner of the windows.", "在窗口的左上角显示一个信息标签。" }},
	{ WindowHighlight, {"Highlight the window cursor points to with a rainbow rectangle.", "用彩虹色方框高亮当前窗口。" }},
	{ WindowESP, {"Display rectangles of the windows.", "绘制一切窗口的方框。" }},
	{ WindowKill, {"Kill the specified window.", "杀掉指定窗口。" }},
	{ WindowFreeze, {"Freeze the specified window.", "冻结指定窗口。" }},
	{ WindowMaster, {"Display a simple window panel, you can control foreground window using hotkeys.", "显示一个简易的窗口面板，你可以通过快捷键控制前端窗口。" }},
	{ PrivateWindow, {"Protect some of your private windows from screenrecording or screenshot.", "防止一些私人窗口被截屏或者录屏。"}},
	{ AntiBrowser, {"Automatically close browsers or URL-links.", "自动关闭浏览器或者链接跳转。"}},
	{ AntiPopups, {"Automatically close some annoying windows.", "自动关闭一些恼人的弹窗。" }},
	{ AntiTopmost, {"Defend against OTHER Topmost windows.", "抵御其他置顶窗口。"}},
	{ CloseEnhance, {"Force Kill its process if a window hasn't closed after Alt+F4 is pressed.", "如果窗口在按下Alt+F4后没有关闭，就杀它的进程。" }},
	{ DialogEscape, {"Close it when any dialog box appear.", "关闭出现的标准对话框。" }},
	{ HideTaskbar, {"Hide the system taskbar.", "隐藏系统任务栏。" }},
	{ UncrossAura, {"Disable the close button of every normal-styled window.", "禁用每一个目标窗口的标准风格关闭按钮。" }},
	{ FreezeAura, {"Freeze every target window.", "冻结每一个目标窗口。" }},
	{ AimAssist, {"Automatically aim at the target window with the mouse.", "自动瞄准目标窗口的右上角。" }},
	{ TriggerBot, {"Automatically click when the cursor is on the close button of a window.", "如果鼠标放在窗口右上角则自动点击。" }},
	{ KillAuraLegit, {"Close every target window after moving the cursor on its close button.", "自动移动鼠标到目标窗口右上角然后关闭它。" }},
	{ KillAura, {"Close every target window.", "自动关闭每一个目标窗口。" }},
	{ MaxAura, {"Maximize every target window.", "最大化每一个目标窗口。" }},
	{ MinAura, {"Minimize every target window.", "最小化每一个目标窗口。" }},
	{ Ruler, {"Draw a window ruler on the screen.", "在屏幕上绘制一个窗口标尺。" }},

	{ ListModules, {"List all the modules of the specified process in Console." , "在控制台列举所有指定进程的模块。"}},
	{ ListDrivers, {"List all the kernel drivers of the system in Console." , "在控制台列举系统的所有内核驱动。"}},
	{ ListServices, {"List all the services of the system in Console." , "在控制台枚举系统的所有服务。"}},
	{ Injector, {"Inject/Uninject DLL into/from the specified process." , "向/从目标进程（取消）注入动态链接库。"}},
	{ RemoteRun, {"Run your command on another process by injecting code." , "通过注入代码，让另一个进程运行你的命令。"}},
	{ Speedhack, {"Speed up or slow down processes by injecting DLL." , "通过注入动态链接库，改变指定进程的运行速率。"}},
	{ GenshinImpact, {"Start Genshin Impact. (Yuanshen, Qi Dong!!) (WIP)", "启动原神。（原神，启动！）（还没做好）"}},
	{ Tasklist, {"Output Tasklist in Console." , "在控制台输出进程列表。"}},
	{ Run, {"Run specified process.", "运行指定进程。"}},
	{ ProcessESP, {"Detect the specified processes." , "探测指定进程。"}},
	{ ProcessKill, {"Kill the specified process." , "杀死指定进程。"}},
	{ ProcessKeep, {"Restart the specified process if it's killed." , "如果指定进程被结束，则重新启动它。"}},
	{ ProcessFreeze, {"Freeze the specified process." , "冻结指定进程。"}},

	{ FileDelete, {"Delete the specified file." , "删除指定文件。"}},
	{ FileCreate, {"Create the specified file." , "创建指定文件。"}},
	{ FileMonitor, {"Monitor file changes in a folder.", "监视一个目录下的文件变化。"}},
	{ FolderClear, {"Clear the specified folder." , "清空指定目录。"}},
	{ TempClear, {"Clear the Windows temp folder.", "清空系统临时目录。"}},
	{ RecyclerClear, {"Clear the Windows Dustbin.", "清空系统回收站。"}},
	{ RootProgram, {"Policies on the disk root Program Glitch." , "针对驱动器根目录下Program文件夹漏洞的政策。"}},
	{ PrivacySpy, {"Collect user's privacy information according to local files, making you nervous", "根据本地文件汇总用户的隐私信息，让你变得紧张"}},
	{ SelfBackup, {"Backup all assets to the backup folder.", "把所有资产备份到backup文件夹。"}},
	{ SelfRestore, {"Restore all assets from the backup folder." , "从backup文件夹恢复资产。"}},
	{ AutoRestore, {"Auto monitor & restore own missing assets." , "自动监视并恢复缺失的资产。"}},

	{ RegMonitor, {"Monitor registry changes. (WIP)", "监视注册表变化。（维护中）"}},
	{ ListHijacks, {"List all Image Hijacks in the registry.", "枚举注册表内所有的映像劫持。"}},
	{ KillHijacks, {"Clear all Image Hijacks in the registry.", "清空注册表内所有的映像劫持。"}},
	{ NoCmd, {"Disable the Command Prompt.", "禁用命令提示符。" }},
	{ NoPowerShell, {"Disable the PowerShell.", "禁用 Powershell。" }},
	{ NoTaskmgr, {"Disable the Task Manager.", "禁用任务管理器。" }},
	{ NoRegedit, {"Disable the Registry Editor.", "禁用注册表编辑器。" }},
	{ NoDesktopIcons, {"Disable the desktop icons. Need to restart explorer.exe.", "禁用桌面图标。需要重启资源管理器。" }},
	{ NoDesktopMenu, {"Disable the desktop menu. Need to restart explorer.exe.", "禁用桌面菜单。需要重启资源管理器。" }},
	{ NoTaskbarMenu, {"Disable the taskbar menu. Need to restart explorer.exe.", "禁用任务栏菜单。需要重启资源管理器。" }},
	{ NoStartMenuChange, {"Disable the change of Start Menu. Need to restart explorer.exe.", "禁用开始菜单的变化。需要重启资源管理器。" }},
	{ NoRun, {"Disable the Run dialog.", "禁用Win+R运行对话框。" }},
	{ NoLogOff, {"Disable the Logoff button.", "禁用注销按钮。" }},
	{ NoSetFolders, {"Disable the Set Folders function in explorer. Need to restart explorer.exe.", "在资源管理器禁用设置文件夹。需要重启资源管理器。" }},
	{ NoFolderOptions, {"Disable the Folder Options in explorer. Need to restart explorer.exe.", "在资源管理器禁用文件夹选项。需要重启资源管理器。" }},
	{ NoWinUpdate, {"Disable Windows Update in explorer. Need to restart explorer.exe.", "在资源管理器禁用系统更新。需要重启资源管理器。" }},
	{ NoWinKeys, {"Disable all the Win-Keys.Need to restart explorer.exe.", "禁用一些Win开头的快捷键。需要重启资源管理器。" }},
	{ NoLockUser, {"Disable the Lock User Workstation operation (including Win+L hotkey).", "禁用锁定用户的操作。包括Win+L快捷键。" }},
	{ RestrictRun, {"Permit and run only certain apps in Windows to run.", "限制系统中所有的程序运行。" }},
	{ NoMSDos, {"Disable the MS-DOS.", "禁用MS-DOS。" }},
	{ NoSmartScreen, {"Disable Microsoft SmartScreen.", "禁用微软 SmartScreen。"}},
	{ NoRemovableDev, {"Disable the removable devices. (UNSTABLE)", "禁用所有可移动设备（不稳定）。" }},
	{ NoRealtimeProtect, {"Disable the Windows Defender Realtime Protection. (UNSTABLE)", "禁用 Windows Defender 的实时保护。（不稳定）" }},
	{ NoUAC, {"Disable the User Account Control. It can take effect without rebooting Windows, actually.", "禁用用户账户控制（UAC）。" }},

	{ AutoTotem, {"Play totem pop animation automatically.", "自动播放爆图腾动画。"}},
	{ HighContrast, {"Enable the High Contrast mode of Windows." , "打开系统的高对比度模式。"}},
	{ BlackCapture, {"In any recording software, this client is in black." , "在任何截图或录屏软件中，客户端是黑屏的。"}},
	{ ScreenSaver, {"Start the system screensaver program.", "启动系统的一个屏幕保护程序。"}},
	{ CloseMonitor, {"Close the monitor." , "发送关闭显示器的信号。"}},
	{ Crosshair, {"Draw crosshair. There are some other functions in Advanced Mode." , "绘制一个准星。在高级模式有一些其他功能。"}},
	{ MouseTrails, {"Enable mouse trails." , "显示鼠标轨迹。"}},
	{ Keystrokes, {"Display keystrokes for gaming." , "显示游戏按键。"}},
	{ Keystrokes2, {"Display keystrokes below dynamically." , "在下方动态显示你的按键。"}},
	{ NoAnimation, {"Disable some of the animations in Windows." , "关闭系统的一些动画。"}},
	{ NoScreenSaver, {"Disable the screensaver." , "禁用屏幕保护程序。"}},
	{ PPLESP, {"Display all the ppl in the left (RTCore64.sys Required).", "在左侧显示所有受保护进程。（需要RTCore64驱动）"}},
	{ SecurityESP, {"Display a malware and antivirus list in the right." , "在右侧显示病毒和杀软列表。"}},
	{ ClipboardESP, {"Display the clipboard contents in the left." , "在左侧实时显示剪贴板内容。"}},
	{ MotionBlur, {"Apply motion blur effects on the screen.", "在屏幕上应用动态模糊。"}},
	{ Background, {"Client background settings.", "客户端背景设置。"}},
	{ TimeDisplay, {"Show current time, and give you a message every half hour." , "显示时间，然后每半个小时报一次时。"}},
	{ Totem, {"Play Totem of Undying animation.", "播放不死图腾的动画。"}},
	{ Watermark, {"Draw Watermark in the center of the screen." , "屏幕中央绘制水印。"}},
	{ WeakView, {"Enable the energy-saving mode of system.", "打开系统节电模式。"}},
	{ Lightness, {"Adjust the gamma of the screen device. (Microsoft: Not Recommended)" , "覆写屏幕伽马亮度值（微软不推荐）。"}},
	{ Spotlight, {"Enable a spotlight when double press Ctrl." , "双击 Ctrl 后在光标的地方显示一个光斑。"}},
	{ Shaders, {"Apply specified shaders to the client." , "应用一些着色器。"}},
	{ Night, {"Enable the Night Mode." , "启动夜间模式。"}},

	{ IPAddress, {"Look up IP Addresses and relevant info of current computer.", "查看本机IP地址及相关信息。"}},
	{ IPHorror, {"Assemble a scary paragraph based on the provided IP address", "根据提供的IP地址组装一个吓人的段落"}},
	{ WallCheck, {"Check if a website is blocked. (Not work)", "检测一个网站是否被墙。（不能正常工作）"}},
	{ Weather, {"Some weather utilities.", "一些天气方面的功能。"} },
	{ LiveStream, {"Some live stream utilities.", "一些直播间的功能。"}},
	{ QQInspect, {"Inspect local QQ basic info if you keeps that glitch.", "如果漏洞存在，则窥探你的基本QQ信息。"}},

	{ AntiAFK, {"Move the mouse periodically to avoid being detected as AFK.", "周期性移动鼠标，防止被检测成挂机。" }},
	{ AntiRickroll, {"Prevent any Never Gonna Give You Up Windows from appearing.", "防止任何 Never Gonna Give You Up 窗口出现。" }},
	{ AutoClicker, {"Automatically Helps you to click very fast.", "自动帮助你飞快地点击鼠标。"}},
	{ BridgeAssist, {"Helps you to bridge in Minecraft.", "在MC辅助你搭路。" }},
	{ ChatAsk, {"Fill your prompt with answer from AI when hotkey is pressed.", "快捷键按下时用人工智能回答你输入的内容。" }},
	{ ChatTranslate, {"Translate your prompt with AI when hotkey is pressed.", "快捷键按下时人工智能翻译你输入的内容。" }},
	{ ChatBilingual, {"Add a translation from AI to your prompt when hotkey is pressed.", "快捷键按下时人工智能把你输入的内容变成双语。" }},
	{ ChatRestruct, {"Restruct your words with AI when hotkey is pressed.", "快捷键按下时人工智能用特定方式重构你输入的内容。" }},
	{ ClipboardTweaks, {"Some useful utilities about clipboard.", "一些剪贴板的实用功能。"}},
	{ MemeTrigger, {"Trigger specified meme when you press RCtrl/RShift + AlphaKey.", "在按下右Ctrl/右Shift+字母键时触发一些特定的梗。" }},
	{ MouseTeleport, {"Teleport the mouse in certain situations.", "在某些场合下传送鼠标。"}},
	{ MouseWatcher, {"Watch the movement and interaction of the mouse.", "监视鼠标移动和交互。"}},
	{ MouseSwap, {"Swap mouse buttons.", "交换鼠标左右键。" }},
	{ NoDoubleClick, {"Disable mouse double click.", "禁用鼠标双击。" }},
	{ NoClipboard, {"Clear the clipboard if it's not empty.", "如果剪贴板有东西，立即清空。" }},
	{ MouseDisabler, {"Disable the mouse with mouse hooks.", "用鼠标钩子禁用鼠标。" }},
	{ SnapTap, {"Automatically releases a previously held key when a new key (A/D) & (W/S) is pressed.", "按下新键（A/D）和（W/S）时，自动释放之前按住的键。"}},
	{ ToggleKey, {"Helps you hold some keys until you repress it.", "帮助你持续按住一些键，直到你再次按下它。"}},
	{ Typewriter, {"Automatically type some paragraphs.", "自动帮你输入段落。"}},
	{ KeyDisabler, {"Disable some keys with keyboard hooks.", "用鼠标钩子禁用一些按键。" }},
	{ KeyLogger, {"Log all the keys pressed to the output folder.", "记录所有的按键到output文件夹。" }},
	{ NoBeep, {"Disable the beep.", "禁用蜂鸣器。" }},
	{ RestartExplorer, {"Restart the explorer.exe. (WIP)", "重启资源管理器（没做好）。" }},
	{ NoIMC, {"Disable global Input Method.", "禁用全局输入法。" }},
	{ Panic, {"Disable all the modules immediately.", "尝试立即关闭所有模块。" }},
	{ Musics, {"Play music.", "播放音乐。"}},
	{ Volume, {"Help you to adjust the volume.", "帮你调节音量。" }},
	{ Mute, {"Mute the current audio device.", "让当前音频设备静音。" }},
	{ Active, {"Keep the client active all the time.", "始终保持客户端窗口为活动窗口。" }},
	{ ForceTopmost, {"Force this client to be topmost with a running thread.", "用线程强制本客户端为置顶窗口。" }},
	{ TaskbarIcon, {"Whether to show taskbar icon.", "是否显示任务栏图标。"}},
	{ OpenUrl, {"Open a URL in the default browser.", "在默认浏览器打开链接。" }},
	{ Screenshot, {"You can take a screenshot using PrintScreen key. ", "你可以用PrtScr键打开截图工具。"}},
	{ Console, {"Enable the Console.", "启动控制台。" }},
	{ Hidden, {"Hide main window and minimize into the tray.", "隐藏主窗口，最小化至托盘。"}},
	{ Restart, {"Restart the client.", "重启客户端。" }},
	{ Exit, {"Quit the client.", "退出客户端。" }},

	{ RTCore64, {"For PPL Settings.", "为受保护进程设定。" }},
	{ DisableHR, {"Kill Huorong Antimalware.", "杀死火绒。" }},

	{ Anti360Ad, {"Punish 360 Ads. (UNSTABLE)" , "惩罚一些360的广告。（不稳定）"}},
	{ Anti360VT, {"Disable the virtualization technology of 360 antivirus.", "禁用360的虚拟化技术。"}},
	{ ScaredUAC, {"Make UAC Prompt move." , "让UAC弹窗移动。"}},
	{ KillEveryone, {"Attempt to kill every process (except 0 and myself)" , "尝试杀死除0和自身外的其他一切进程。"}},
	{ KillAV, {"Kill Every Antivirus Process registered in my process profile." , "尝试杀死注册在档案中的杀软进程。"}},
	{ CloseAV, {"Take measures to close some Antivirus software. (WIP)", "采取一些措施关闭一些杀软。（没做好）"}},
	{ KillMalware, {"Kill Every Malware Process registered in my process profile." , "杀死每一个已注册的恶意程序进程。"}},
	{ FreezeExplorer, {"Attempt to freeze explorer.exe (Failure may be not real)", "尝试冻结资源管理器。（失败可能只是表象）"}},
	{ FreezeEveryone, {"Attempt to freeze every process (except 0 and myself)", "尝试冻结0和自身以外的一切进程。"}},
	{ UnfreezeEveryone, {"Attempt to unfreeze every process (except 0 and myself)" , "尝试解冻0和自身以外的一切进程。"}},
	{ PPLButcher, {"Attempt to kill every PPL (RTCore64 Required, Not Recommended).", "尝试解除每一个受保护进程的保护。（需要 RTCore64 驱动，不推荐）"}},
	{ ACGButcher, {"Attempt to disable the DynamicCodePolicy of every process.", "尝试关闭一切进程的动态代码政策。"}},
	{ TrustedInstaller, {"Granted with TrustedInstaller privileges. (UNSTABLE)" , "重启客户端获得受信任安装者权限（不稳定）。"}},
	{ RemoteKillHR, {"Kill Huorong Antimalware using remote thread. (WIP)", "用远程线程让其他进程杀火绒（没做好）。"}},
	{ Masquerade, {"Masquerade as explorer.exe by modifying PEB.", "修改PEB伪装成资源管理器。"}},
	{ NoNotification, {"Attempt to disable Windows Notification. (WIP)", "尝试关闭系统通知（没做好）"}},
	{ RuinAura, {"Ruin every target window. (WIP)" , "搞坏每一个目标窗口（没做好）"}},
	{ SelfDestruct, {"Delete myself (exe) immediately.", "立即删除客户端自身EXE。"}},
	{ SelfUninstall, {"Uninstall this client (entire folder) immediately.", "立即卸载整个客户端。"}},
	{ HideProcess, {"Global Inject JDProcHide.dll hooking ZwQueryInformationProcess (WIP).", "全局注入来隐藏自身进程。（没做好）"}},
	{ Vape, {"Draw Vape Logo. It's kind of cool", "绘制电子烟的标志。有点帅。"}},
};

string GetModuleDescription(ModuleID mid);